name: Configuration_variable

on:
  workflow_dispatch:  # This line makes the workflow run only when triggered manually

env:
  name: naveen

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World
        run: echo "${{ env.name }} from ${{ vars.department }} department"
