name: workflow-secrets

on:
  workflow_dispatch:  # This line makes the workflow run only when triggered manually

env:
  name: naveen

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      country: india

    steps:
      - name: Hello World
        run: echo "Hello, my name is ${{ env.name }}, our secret mission is ${{ secrets.mission }}"