name: Self-hosted-runner-workflow

on:
  workflow_dispatch:    # This line makes the workflow run only when user's manual trigger (eliminates automatic trigger on push)

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: helloworld
        run: echo 'Hello my name is naveen'